services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      sh -c "mkdir -p /var/www/html/uploads &&
      chown -R www-data:www-data /var/www/html/uploads &&
      chmod -R 0775 /var/www/html/uploads &&
      apache2-foreground"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - uploads_data:/var/www/html/uploads
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    networks:
      - edge
      - app_net

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    networks:
      - app_net

volumes:
  pgdata:
  uploads_data:

networks:
  edge:
    driver: bridge
  app_net:
    name: sortir_dokumen_app_net
    driver: bridge
    internal: true
